# Enter an email configuration. Remove this config entirely, if you do not want so send mails.
# Note that this requires you to have configured TrueNAS email at Alerts -> Email.
email:
  fromaddr: "admin"
  recipients: "admin"

# List any pools you want to backup, where the label is the name of the pool (also the label under /dev/disk/by-label)
# a limitation is that each pool name can be configured only once. As children, include:
# - autobackup_parameters: the command line arguments you want to pass to zfs-autobackup
# - split_parameters (optional, true by default): controls shell-style word splitting on zfs-autobackup parameters.
#                     E.g. if you use '--set-properties readonly=on' this needs to be true (or unset).
# - passphrase (optional): encryption passphrase
pools:
  OnePool:
    autobackup_parameters:
      - "-v"
      - "--debug"
      - "--clear-mountpoint"
      - "--set-properties readlonly=on"
      - "--keep-source=10,1d1w,1w1m,1m1y"
      - "--keep-target=10,1d1w,1w1m,1m1y"
      - "zfs-label"
      - "pool/path/to/target/dataset"

  AnotherPool:
    split_parameters: false
    autobackup_parameters:
      - "-v"
      - "--debug"
      - "--clear-mountpoint"
      - "--keep-source=10,1d1w,1w1m,1m1y"
      - "--keep-target=10,1d1w,1w1m,1m1y"
      - "zfs-label2"
      - "pool/path/to/target/dataset2"
    passphrase: "verysecret"
